### ISSUE TITLE
[Feature Request] emacstv-agenda-refresh-list (to refresh the videos.org file)

### ISSUE THREAD

**Issue by danrobi11** [emacstv/emacstv.github.io#15]
Hi.
Im not really a powerful user with coding skills. So this might not be needed.

I  figured so far that `emacstv.el` generate the `videos.org` file. From that file, we have the full list of video's available.
I was wondering, in order to just refresh the `videos.org` file, what do we need to do?
Is a `emacstv-agenda-refresh-list` function would make sense in order to just refresh the `videos.org` file. Or, I just didnt find the good command yet?

Anyhow, with `emacstv-build` the file `videos.json` and `videos.rss` gets updated.  Not the `videos.org` file tho. 
Tbh, I rather read the `videos.org` file then the `.json` / `.rss` file. The `videos.org` file Just feels better to read for my eyes ;)

That's how I plan to use `emacstv.el`. I'll just refresh the `videos.org` file then run a search in that file. Bingo! No need for extra stuff for me on my end.

**Comment by xenodium** [comment]
> I was wondering, in order to just refresh the videos.org file, what do we need to do?

videos.org itself is the canonical source/feed and crafted semi-manually. This is what we ask submitters to modify in pull requests https://github.com/emacstv/emacstv.github.io?tab=readme-ov-file#add-videos.

Everything else (ie. rss/json) is derived from videos.org. There are some helpers to ease videos.org additions (but these still need some manual intervention).

AFAIK, we don't yet have anything to automatically pull from anywhere (@sachac please correct me if otherwise).

> Tbh, I rather read the videos.org file then the .json / .rss file. 

The latter are a little funky to consume directly. For .rss, elfeed does a good job presenting items. @sachac has been adding some native consumption commands too like `emacstv-play` (with fuzzy search) and `emacstv-play-random`.

**Comment by sachac** [comment]
If you want an agenda view, you can use emacstv-agenda-search to search and emacstv-play-at-point to play at point. Is that what you're looking for?

I don't automatically pull in new videos yet, but I plan to update things weekly as I do Emacs News and will probably figure out some kind of RSS input someday. :)

**Comment by danrobi11** [comment]
Maybe I explained wrong. 

When I run `M-x emacstv-build` both the  `.json` and `.rss `get's updated in my `emacstv` directory.
I was asking if somehow the `videos.org` file in my `emacstv` directory could be also updated when I run `emacstv-build`. As it's the more human readable file in between the 3 files. That's why I was thinking about maybe a new function that would update the `videos,org` file in my `emacstv` directory.

I like thing's simple. Me I'd just go run a search for what i'm looking for in the `videos.org` file. Copy the desired video link from the `videos.org` file and Voila!. 

Anyhow, feel free to close the issue if that doesnt make sense to you. 

Thank's again for `emacstv.el` It's such a great idea. Congrats!

**Comment by sachac** [comment]
Oh, do you mean pulling an update from the repository? If you checked it
out with git clone, I think you can use git pull, or you can use Magit to
pull it. If you're using use-package, I think you can tell Emacs to upgrade
the package. I'll look up the exact instructions when I get back to my
computer.

**Comment by danrobi11** [comment]
Oh ya, that's smart! It works indeed with  `auto-package-update-now`. 
 Im all good with that. Good day! Closing.
